### ISSUE TITLE
Remove Campaigns feature

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#13]
Because it creates a second shortcut in the Android launcher.

Probably as was done here:
https://github.com/brion/apps-android-commons/commit/ed2cec4ce3a87b57d630f2d830469acb9fcf762f

Plus removing dead code.

**Comment by misaochan** [comment]
Do we want to remove the entire Campaigns feature or just the extra shortcut in the launcher? Removing the shortcut and the associated call to the Campaigns service is fairly easy. However there is a whole Campaigns folder that can't seem to be removed without extensive modification of the code in multiple places. Do we want all of that removed as well, or should we keep it in case others want to revive this feature in the future, and just remove the extra shortcut for now?

**Comment by nicolas-raoul** [comment]
I am in favour of removing the whole thing. Campaigns was probably an
experiment that did not get traction. Better simplify rather than carry
this complexity waiting for a very improbable revival.

**Comment by nicolas-raoul** [comment]
Implemented by @misaochan
