### ISSUE TITLE
Urgent: Application suspended

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#132]
Uh, wow. So I uploaded another APK with the brand etc reverted to the nobrand branch, and now the application is suspended. :/ I think this is pretty bad because it means nobody can download it at the time, and anyone who tries to access our Google Play site will get this. (Also pretty bad timing since the IEG results will come out today, and they might want to do final checks)

@nicolas-raoul , do you think you could contact the Wikimedia legal team and have them talk to Google Play?

![suspended](https://cloud.githubusercontent.com/assets/3611199/16143810/44e86628-34c3-11e6-9a91-e7c06b61e7dd.jpg)

**Comment by misaochan** [comment]
Geez, now it has been removed, not just suspended. Wtf is Google doing?! Surely they shouldn't be removing apps automatically, there should be a real person checking the evidence before deciding to do that?

**Comment by alexs08** [comment]
I'm guessing this was because Google thought you didn't own the rights to the app. What details did Google give you in their email?

**Comment by misaochan** [comment]
Not sure, the email was sent to nicolas. But yeah, it's probably because of that. We sent the signed trademark license agreement to Google before the app was removed, though, so the removal was rather odd. Nicolas mentioned in #129 that he asked Wikimedia to contact Google, so we probably just have to wait now.

**Comment by nicolas-raoul** [comment]
I received a reply from the appeal:

> Hello Nicolas,
> 
> Thank you for contacting the Google Play Team.
> 
> We’ve accepted your appeal and your app Wikimedia Commons (fr.free.nrw.commons) has been reinstated. For the app to appear on the Play Store, you’ll need to sign into your Developer Console and click "Submit update" to submit your app again.
> 
> If the option to resubmit is not available, please make a small change (such as adding and deleting a space in your Description in the Store Listings) to reactivate the button.
> In the future, if you have proof of permission you can submit it to our team proactively using this form: https://support.google.com/googleplay/android-developer/answer/6320428
> 
>     The link can also be found on your Store Listing page underneath the box for Full Description.
> 
> If you're an AdMob publisher, you'll need to contact the AdMob team to re-enable ad serving:
> https://support.google.com/admob/contact/appeal_policy_violation
> 
> The AdMob policy team will review your app(s) and decide whether to re-enable ad serving.
> 
> Please let me know if you have any other questions or concerns.
> 
> Thanks for supporting Google Play!
> 
> Regards,
> Bruce
> The Google Play Team

I resubmitted the app as described, it is now "Processing update".

**Comment by misaochan** [comment]
Whew, good to hear that!

**Comment by nicolas-raoul** [comment]
Yeah, losing our hard-earned 336 users (they would stop receiving updates) would have been quite a drawback.

Looks like we're back :-) https://play.google.com/store/apps/details?id=fr.free.nrw.commons

**Comment by nicolas-raoul** [comment]
Let's revert to the WMF name/logo then :-)

**Comment by misaochan** [comment]
Haha, you sure? Maybe we should wait til WMF does the transfer to their account, just in case?

**Comment by nicolas-raoul** [comment]
Now that they have acknowledged the contract, I think it is safe.

**Comment by misaochan** [comment]
Okay, submitted.

**Comment by misaochan** [comment]
Btw @nicolas-raoul , nemo pinged you on my grant page about localization crowdsourcing: https://translatewiki.net/wiki/Thread:Support/Former_WMF_app_now_community-maintained,_where_to_crowdsource_localization%3F

**Comment by nicolas-raoul** [comment]
Thanks for the tip!
I am not a fan of adding as committers people who have never worked on the project, but apparently they are very trustable persons so I add them for the sake of getting their expertise on i18n matters.
