### ISSUE TITLE
Allow developers to use Instant Run

### ISSUE THREAD

**Issue by whym** [nicolas-raoul/apps-android-commons#138]
"Instant Run" is a useful feature of Android Studio. I use it for developing other apps, and it is a pain that I have to disable it when developing this Commons app and re-enable when developing other apps.

It looks like the blocking issue is 
``
java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to fr.free.nrw.commons.CommonsApplication
``
that can happen in the onCreate method of `ContributionsContentProvider`. (#112) The cast is done when the class tries to obtain the DB helper from the activity instance.

Could it somehow be avoided, perhaps by making `DBOpenHelper` a singleton accessible by all classes directly?

**Comment by nicolas-raoul** [comment]
If we could avoid having to disable Instant Run, that would be wonderful indeed :-)
If you find a way to fix the problem, we would happily accept your pull request.

**Comment by whym** [comment]
Thanks for merging. I would suggest updating README and closing this issue, if we see no bad side-effect it in a week or so.

**Comment by nicolas-raoul** [comment]
OK!
Feel free to do that when you see fit :-)

**Comment by nicolas-raoul** [comment]
And thank you for getting involved in the app!
As you know, there are many [issues](https://github.com/nicolas-raoul/apps-android-commons/issues) waiting for someone to take care of them :-)

**Comment by misaochan** [comment]
Fixed by @whym , thanks!
