### ISSUE TITLE
Package naming issue

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#14]
After importing the project into IntelliJ, there seems to be a namespace problem. In the project file structure on the left, most of the source files are contained within the org.wikipedia.commons package, but in the code they are declared as `package fr.free.nrw.commons;`

![commons](https://cloud.githubusercontent.com/assets/3611199/10266283/8fcc78a2-6ab4-11e5-9625-ab91640141fe.jpg)

**Comment by nicolas-raoul** [comment]
Yes, I did not take the time to rename the folders... I use command-line compilation, which did not complain about that, but indeed that needs fixing. That would be a good microtask!

**Comment by misaochan** [comment]
Oops, just read that I should have referenced this issue in my commit. Will try to remember that next time. Anyway, I submitted a pull request (that I think fixes the problem).

**Comment by misaochan** [comment]
Fixed. :)
