### ISSUE TITLE
Send push notifications if a nearby location needs an image

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#154]
Suggested by Tobias1984 on my grant page:

> Would be good if users could set up a Radius where they get push notifications if a missing image location is for example just 1 km away. --Tobias1984 (talk) 09:40, 3 July 2016 (UTC)

I think this could be doable later on after the 'display nearby images lacking articles' task has been completed, what do you think? If we do this we should probably have a setting for users to choose whether they want the notifications or not.

**Comment by nicolas-raoul** [comment]
Nice idea!
We would probably need to run some server-side code to achieve this.
I am not sure we can use Google's push service, so anyone feel free to post ideas of the technology we could use to develop this feature, thanks!
Client-side library must be open source and service must be compatible with Wikimedia's privacy policy.

**Comment by nicolas-raoul** [comment]
Sounds like #79 if I am not mistaken?

**Comment by misaochan** [comment]
Oh, yeah, sorry. I missed that one. :)
