### ISSUE TITLE
"Take photo" action fails to save and upload photo on Android 6 (API 23)

### ISSUE THREAD

**Issue by whym** [nicolas-raoul/apps-android-commons#164]
Apparently the save button (check mark) does not work for Android 6 as it does for older Android. I tried Nexus 5 (Android 6) and an emulator (Android 6, API level 23), and experienced the issue with both. Another emulator with Android 5.1, API level 22 went without the issue.

Instead, on Android 6 I was able to take a photo with the default Camera app directly, and go back to the Commons app to find it in the gallery and upload, though.

See also https://groups.google.com/d/msg/commons-app-android/Dtxo2j4ylrg/gu3xRiDuBAAJ

**Comment by misaochan** [comment]
Oh, thanks for letting us know! My real device is using an older version of Android, so I didn't notice the problem.

**Comment by whym** [comment]
Um, actually I am not able to reproduce it any more.

I am guessing that I might have been on the build of a local, possibly broken branch. Sorry if that was the case.

**Comment by misaochan** [comment]
Does the current release (v1.17) work properly in your real device then? I can't reproduce the bug on emulator, but I don't have a real device with api 23 to test with.

**Comment by whym** [comment]
Here are latest test results. This time it looks like stably reproducible.

This time, I downloaded the app from Play Store on a physical device with Android 6.0.1. Followed this procedure: 1. Initial settings of the app -> 2. "Take photo" -> 3. Enter title and description -> 4. Tap "Share" button. Saw a crash. File was not uploaded.

After the crash, I manually gave the app the "storage" permission. The next attempt (2., 3., 4.) went fine.

And then, I manually revoked the app's permission, and the crash would happen again under the same procedure (2., 3., 4). 

By the way, I am seeing the same crash pattern on emulator as well after I turned off the storage permission.

**Comment by misaochan** [comment]
Thanks @whym ! Will look into it.

**Comment by misaochan** [comment]
Managed to reproduce the bug and got the crash log:

```
07-12 17:05:00.097: E/DatabaseUtils(2035): Writing exception to parcel
07-12 17:05:00.097: E/DatabaseUtils(2035): java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/74 from pid=3802, uid=10058 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
07-12 17:05:00.097: E/DatabaseUtils(2035): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
07-12 17:05:00.097: E/DatabaseUtils(2035): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
07-12 17:05:00.097: E/DatabaseUtils(2035): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:471)
07-12 17:05:00.097: E/DatabaseUtils(2035): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:416)
07-12 17:05:00.097: E/DatabaseUtils(2035): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:313)
07-12 17:05:00.097: E/DatabaseUtils(2035): 	at android.os.Binder.execTransact(Binder.java:453)
07-12 17:05:00.097: E/ImageLoader(3802): Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/74 from pid=3802, uid=10058 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
07-12 17:05:00.097: E/ImageLoader(3802): java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/74 from pid=3802, uid=10058 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
07-12 17:05:00.097: E/ImageLoader(3802): 	at android.os.Parcel.readException(Parcel.java:1599)
07-12 17:05:00.097: E/ImageLoader(3802): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
07-12 17:05:00.097: E/ImageLoader(3802): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
07-12 17:05:00.097: E/ImageLoader(3802): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
07-12 17:05:00.097: E/ImageLoader(3802): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1104)
07-12 17:05:00.097: E/ImageLoader(3802): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
07-12 17:05:00.097: E/ImageLoader(3802): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
07-12 17:05:00.097: E/ImageLoader(3802): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromContent(BaseImageDownloader.java:156)
07-12 17:05:00.097: E/ImageLoader(3802): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:88)
07-12 17:05:00.097: E/ImageLoader(3802): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.getImageStream(BaseImageDecoder.java:84)
07-12 17:05:00.097: E/ImageLoader(3802): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:70)
07-12 17:05:00.097: E/ImageLoader(3802): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:290)
07-12 17:05:00.097: E/ImageLoader(3802): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:250)
07-12 17:05:00.097: E/ImageLoader(3802): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:131)
07-12 17:05:00.097: E/ImageLoader(3802): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-12 17:05:00.097: E/ImageLoader(3802): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-12 17:05:00.097: E/ImageLoader(3802): 	at java.lang.Thread.run(Thread.java:818)

```

**Comment by misaochan** [comment]
Hmm. Actually, when you enter the title/desc screen, storage permissions are checked and the user is prompted to accept them. I don't think there is anything we can do if the user refuses? I could wrap the relevant code in something that doesn't crash but instead says 'Sorry, can't upload this picture without storage permissions' I guess?

**Comment by nicolas-raoul** [comment]
Yes, explain why the permission is needed, before asking for it again. I wonder if looping on this is OK regarding to Android guidelines.

**Comment by misaochan** [comment]
Might be a bit tricky, since we have to catch the exception in UploadController (for camera) or ContributionController (for gallery), and AFAIK runtime permissions can only be requested/granted in an activity or fragment. Is it okay to just say 'Please accept the storage permission and try again'?

**Comment by misaochan** [comment]
Alternatively, what do you think of the 'Permission Everywhere' library suggested at http://stackoverflow.com/questions/32292675/how-to-request-permissions-from-a-service-in-android-marshmallow ?

**Comment by nicolas-raoul** [comment]
PermissionEverywhere looks useful indeed!
And it is Apache 2.0

**Comment by whym** [comment]
If the storage permission is required for both of the upload and gallery functions, can it be requested earlier? (e.g., the initial step where you input account name and password.) I think it's reasonable, because without the two features the app is almost useless.

**Comment by misaochan** [comment]
PermissionsEverywhere requires min SDK to be 15. Currently ours is 11. That's 4.0.3, which excludes only 0.6% of our app's users according to the Google Play statistics. Should be okay?

**Comment by misaochan** [comment]
Okay, I've implemented a check where if the user clicks the Upload button without the appropriate permissions, he will be asked for it again and won't be allowed to proceed until he accepts. 'Permission Everywhere' wasn't required for the camera fix since I could put the permission check in ShareActivity. 

If anyone with a API 23 real device could please test the pull request on your device (@whym ?), would be really grateful. I've submitted so many blank/useless camera photos (because there's nothing else I can submit with an emulator) that the Commons folks must be quite pissed at me, lol.

**Comment by misaochan** [comment]
Sorry @nicolas-raoul , I'll reopen this in hopes of getting real device feedback on the code. :)

**Comment by whym** [comment]
I would be against introducing a new dependency just for fixing this bug. Every new dependency increases the maintenance cost in the long run (and also the APK size).

For this bug, I think there are other approaches worth considering:

If the storage permission is needed for both of the photo feature and gallery feature to be functional, then why not request it at an earlier point? (e.g., installation, first log in/account creation, etc.) When it becomes a part of the installation/initialization step, this issue will disappear.

On the other hand, if the permission is not absolutely needed (=if the photo feature and gallery feature can function to a certain extent without it, probably by having everything on memory), then crash should not happen even when the user does not give the permission. An "infinite loop" for asking for it should not happen either.

**Comment by misaochan** [comment]
The new dependency was not introduced, as I found a way around it. 

I think the user can still browse their old pictures if they really want to without the storage permission, they just cannot upload. Hence the block at the upload (title/desc) screen. An infinite loop should not happen, please do let me know if it does.

**Comment by whym** [comment]
> The new dependency was not introduced, as I found a way around it. 

Sorry for not realizing that. If it was not introduced, can this line for repositories be reverted as well, I guess? 
https://github.com/nicolas-raoul/apps-android-commons/blob/00ab7dc339fe796b7d6316c2aa740dc68e4dc47d/app/build.gradle#L3

I tested this (00ab7dc339fe796b7d6316c2aa740dc68e4dc47d) on the physical device and went fine. Saw a dialog for permission after pressing "Share". First declined and then accepted. File was uploaded. Good work!

**Comment by misaochan** [comment]
Thanks @whym ! And thanks for fixing the gradle script, I missed that line indeed. :)
