### ISSUE TITLE
Prevent upload of pictures that have been uploaded already

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#174]
Should be shown before the user wastes time entering title/description/categories.

Commons has an API to check the presence or not of a file, it works by sending the checksum: http://opendata.stackexchange.com/a/7314/754

The request might take time, and most often is negative (not duplicate), so better not make it blocking/synchronous.
Maybe launch the request asynchronously immediately after showing the title/description screen, and abort this screen if the picture is a duplicate?

**Comment by misaochan** [comment]
Is this the same as #77 ?

**Comment by nicolas-raoul** [comment]
wow I totally forgot about this thanks!
