### ISSUE TITLE
Various feedback on v1.17

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#177]
Any thoughts on these?

(A) By Arun Prakash (11 Jul):

> 1) Way to add wiki code using description is missing
> 2) Geo Coordinates are not picked up from the meta data of the file
> 3) uploads as jpeg, will be nice if it is uploaded as jpg

I don't understand what is meant by (1) and (3)... Do you? And (2) is probably the same as #35 ?

(B) By Shyamal (12 Jul):

> 
> Would be useful to know what phone photos have already been uploaded.
> Would be good to limit my uploads list of photos to what has been uploaded from the device.

I guess the first is what inspired #175 ? :) Do you agree with the second? I don't know if other users would have a similar preference, personally I prefer to see all uploads, especially when people change devices frequently.

**Comment by nicolas-raoul** [comment]
A1) Created https://github.com/nicolas-raoul/apps-android-commons/issues/178
A2) Yes I guess
A3) Waiting for Shyamal's answer
B1) Created #175
B2) Created #179

**Comment by misaochan** [comment]
Thanks Nicolas!

Haha, minor note but A(3) is suggested by Arun and not Shyamal... hopefully you sent it to the right person? :)

**Comment by nicolas-raoul** [comment]
Fixed thanks! :-)

**Comment by nicolas-raoul** [comment]
I guess this can be closed?

**Comment by misaochan** [comment]
Yup!
