### ISSUE TITLE
Add Travis CI badge

### ISSUE THREAD

**Issue by whym** [nicolas-raoul/apps-android-commons#201]
@nicolas-raoul: Please log in to Travis CI and activate https://travis-ci.org/nicolas-raoul/apps-android-commons . And then we can use the image file of the badge in the README file.

Image file: https://api.travis-ci.org/nicolas-raoul/apps-android-commons.svg

You could use https://api.travis-ci.org/whym/apps-android-commons.svg but I cannot guarantee that my fork is always up-to-date.

**Comment by nicolas-raoul** [comment]
I activated :-)
