### ISSUE TITLE
Move from bits/event.gif to wikimedia/beacon

### ISSUE THREAD

**Issue by Krinkle** [nicolas-raoul/apps-android-commons#220]
The internal bits.wikimedia.org domain has been deprecated for about a year now and is on its way to be decommissioned. See also <https://phabricator.wikimedia.org/T107430>.

`event.gif` has also been replaced with a `/beacon/event` entry on all text domains. Bits still supports event.gif, but the new domains only support `/beacon`.

* `bits.wikimedia.org/domain:/load.php` -> `https://domain/w/load.php`
* `bits.wikimedia.org/event.gif` -> `https://www.wikimedia.org/beacon/event`

Since users may take time to upgrade their installations, this update should be released as soon as possible.

**Comment by whym** [comment]
+1 for a new release as soon as possible. Are we ready to deliver it with other recent commits so far, or should we cherry pick this and release it as a minor update?

**Comment by nicolas-raoul** [comment]
Thanks!
By the way, what is this?
Is it related to https://meta.wikimedia.org/wiki/Dynamic_links_to_external_resources#What_is_BEACON.3F?
If not, is there an explanation page somewhere, in order to judge whether we actually need that feature or can scrap it altogether?
Thanks!

**Comment by whym** [comment]
It appears to be for https://grafana.wikimedia.org/dashboard/db/eventlogging-schema?var-schema=MobileAppLoginAttempts and a few other charts. (I had to reload it after loading the page, and tweak the range using the upper right tab, to see the chart)

**Comment by Krinkle** [comment]
@nicolas-raoul No, it does not relate to <https://meta.wikimedia.org/wiki/Dynamic_links_to_external_resources#What_is_BEACON.3F>.

The entry points used here (both `event.gif` and `/beacon/*`) are for EventLogging (see [mw:Extension:EventLogging](https://www.mediawiki.org/wiki/Extension:EventLogging) and [wikitech:Analytics/EventLogging](https://wikitech.wikimedia.org/wiki/Analytics/EventLogging)).

The way it works is basically that a client hits that url with a query string. The request (just like as all other requests to this domain) are handled by Varnish and logged to Kafka (from which e.g. pageview statistics are calculated).

Varnish is preprogrammed to completely ignore the request and immediate return an empty `HTTP 204 No Content` response. So it's a "log and forget it" entry point. The internal aggregation and computation happens in the background.

There, from Kafka, they are further processed and eventually turned into numbers in a graph and rows in a database. What graph or database specifically is up to the consuming team that set up that individual EventLogging schema. See <https://meta.wikimedia.org/wiki/Schema:MobileAppLoginAttempts> for example.

**Comment by whym** [comment]
@nicolas-raoul did you mean to close this already? I thought it wasn't decided yet to release or not.

**Comment by nicolas-raoul** [comment]
@whym:
In my mind, for development issues, "closed" means "fixed in Git".
Google Play should be impacted soon.

**Comment by misaochan** [comment]
If desired, I can release this (along with a hopefully quick bugfix) next week. Am currently working on the in-app sign in feature but that won't be ready in time, so we can probably do this release first.

**Comment by nicolas-raoul** [comment]
I don't think it is ultra-urgent, right? I guess it can wait for a few days, so don't worry @misaochan . No crashes, no data corruption, at worse we will pollute a decommissioned log file for a few more days, or some empty requests will fail against a decommissioned server.
Cheers!

**Comment by whym** [comment]
> No crashes, no data corruption, at worse we will pollute a decommissioned log file for a few more days, or some empty requests will fail against a decommissioned server.

True, the bad things (including failures to capture data for analytics purposes) that may happen are only on the servers for logging - no harm to users and Wikimedia Commons. Still, I would hope a new release sooner than later.

The timeline for completing T107430 is not immediately clear to me, but I *guess* that they are in the process of making sure of getting everyone (different apps, bots, etc) ready for the decomission, without having a hard deadline yet. That means that they are, in part, waiting for us. If a new release can happen next week, that sounds great.

I will keep an eye on <https://phabricator.wikimedia.org/T107430> and <https://phabricator.wikimedia.org/T132969>.

**Comment by nicolas-raoul** [comment]
Understood! :-)
By the way, since nobody in the Commons app team is actually using this data (to my knowledge), nobody should feel obligated to "wait for us". Cheers!

**Comment by misaochan** [comment]
Released in v1.24 today.
