### ISSUE TITLE
"Uploading XXX" notification stays forever

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#27]
Probably due to starting an upload and then beginning another one before the first one is finalized.
![screenshot_2015-11-01-15-45-38](https://cloud.githubusercontent.com/assets/99590/10877102/78f9d56e-8186-11e5-8d7f-1e76c0fccac6.png)

**Comment by misaochan** [comment]
Hmm, I just tried that (beginning another one before the first one is finalized) and the notification disappears after the second one is done. Might be randomly occurring?

**Comment by nicolas-raoul** [comment]
I am not exactly sure how to reproduce it... let's keep that under surveillance.
Anyone seeing this problem, please provide as much information as you can, thanks!

**Comment by misaochan** [comment]
Never been able to reproduce this so far... :(

**Comment by nicolas-raoul** [comment]
I haven't seen it for a while either.
I close for now, anyone experiencing this bug please reopen!
