### ISSUE TITLE
Change text on 'About' screen in all languages

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#39]
AboutActivity currently says "Bugs at Bugzilla", which might have worked once upon a time but now redirects to http://phabricator.wikimedia.org which is a bit too general. Perhaps it might be better to link to the GitHub 'issues' page here instead?

**Comment by nicolas-raoul** [comment]
Sure! Good catch.

**Comment by misaochan** [comment]
Fixed

**Comment by tobias47n9e** [comment]
It seems to be fixed only in the English version. Searching for "https://bugzilla.wikimedia.org/enter_bug.cgi?product=Commons%20App\", currently still has 49 results.

I also noticed that the main README.md does not mention where people can help with the localization of the app.

I suggest reopening the issue, until both things are resolved.

**Comment by nicolas-raoul** [comment]
@tobias47n9e : The URL in your post does not seem to work in my browser, maybe it is linked to your session or something? A manual search does not show any recent bug. Woiuld you mind posting a screenshot?

By the way, localisation is non-existent right now.
I really hope this gets fixed soon: https://translatewiki.net/wiki/Thread:Support/Former_WMF_app_now_community-maintained,_where_to_crowdsource_localization%3F
There is an issue about that: https://github.com/nicolas-raoul/apps-android-commons/issues/62
Meanwhile the string manually could be removed manually, I guess.

**Comment by tobias47n9e** [comment]
@nicolas-raoul This is the link to the search: 

https://github.com/nicolas-raoul/apps-android-commons/search?utf8=%E2%9C%93&q=%22https%3A%2F%2Fbugzilla.wikimedia.org%2Fenter_bug.cgi%3Fproduct%3DCommons%2520App%5C

The link immediately redirects to "https://phabricator.wikimedia.org/"

Here is a screenshot of the German version with the wrong name for the link and the URL mentioned above:

![screenshot_2016-08-07-14-44-13](https://cloud.githubusercontent.com/assets/6953323/17463654/da55e8fa-5cca-11e6-9e36-3f7abb300155.png)

**Comment by nicolas-raoul** [comment]
Done :-)
```
find . -type f -print0 | xargs -0 sed -i 's/Bugzilla/Github/g'
find . -type f -print0 | xargs -0 sed -i 's/https:\/\/bugzilla.wikimedia.org\/enter_bug\.cgi?product=Commons%20App/https:\/\/github.com\/nicolas-raoul\/apps-android-commons\/issues/g'
```
