### ISSUE TITLE
License translation part is broken

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#42]
By Hallibut:

> I can then proceed to take a photo, fill in the title and description (the text below reads "The image will be shared under CCu00A0Uznanie autorstwa-Na tych samych warunkachu00A03.0" - clearly it should be "CC-Uznanie autorstwa-Na tych samych warunkach", or something along those lines; all the license available in settings have wrong names as well).

**Comment by Halibutt** [comment]
I'm here in case you need me :)

**Comment by nicolas-raoul** [comment]
Hello! :-)

You can edit the translation files here, and send us a pull request: https://github.com/nicolas-raoul/apps-android-commons/tree/master/commons/res

**Comment by domdomegg** [comment]
Fixed in PR #113

**Comment by misaochan** [comment]
Shall we close?

**Comment by domdomegg** [comment]
Think we can now

**Comment by misaochan** [comment]
Thanks @domdomegg !
