### ISSUE TITLE
Pressing "Back" on category screen by mistake is fatal

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#58]
I mistakenly pressed the back button, and now no way to add categories

**Comment by misaochan** [comment]
Maybe if a user presses 'back' while on category screen, we could show a dialog asking something like "Are you sure you want to leave? This image has no categories. Yes/No"?

**Comment by nicolas-raoul** [comment]
Sounds good!

**Comment by misaochan** [comment]
Will be implementing this in Phase 2 of my IEG.

**Comment by misaochan** [comment]
Okay to close?

**Comment by nicolas-raoul** [comment]
OK, works great!
