### ISSUE TITLE
Let people create a Wikimedia account within the app

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#6]

**Comment by misaochan** [comment]
I agree that this would be very useful. Perhaps I could put in a link on the login form activity, to the Sign Up page on the web app? Or is there a need to have the entire signup process done within the app?

**Comment by nicolas-raoul** [comment]
If the Wikipedia app has in-app registration we could re-use it, otherwise a link is probably enough indeed.
