### ISSUE TITLE
Warn users if they submit an image without categories

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#61]
From https://groups.google.com/forum/#!topic/commons-app-android/-2hqB6oAsF8

If a user presses 'save' without any categories selected, they can potentially be shown a dialog warning them that their picture is likely to be deleted if it is submitted without any categories. 

Maybe this could tie in with issue #58 , so this dialog is shown both when back button is pressed and when save button is pressed, if no categories selected?

**Comment by misaochan** [comment]
Is this OK to close?

**Comment by nicolas-raoul** [comment]
OK! I will test it today.

**Comment by misaochan** [comment]
Great, thanks!

**Comment by nicolas-raoul** [comment]
Just tested, nice!
