### ISSUE TITLE
Get WMF to update their Github description/README to link to us

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#63]
Problems:
- Some users who want to report a bug go to Google, search for the app's project page, and find https://github.com/wikimedia/apps-android-commons which links to now-defunct Bugzilla. Result: no feedback for us, and frustrated users.
- When I advertise the app, I get negative feedback saying "Why do you advertise the fork rather than the original?" ([example](http://meta.stackoverflow.com/a/315023/226958)).
- https://github.com/wikimedia/apps-android-commons says "*our actual code is hosted with Gerrit*" which scares away most potential contributors. And for those who don't give up and go search Gerrit, no code is actually there. It can be hard to find our fork.

Solution: https://github.com/wikimedia/apps-android-commons should be modified this way:

- Github project description: `This project is now maintained by volunteers at https://github.com/nicolas-raoul/apps-android-commons`
- Content of file README.md:

```
Initially started by the WMF, this app is now maintained by volunteers at https://github.com/nicolas-raoul/apps-android-commons
Please report any bug there.
```

**Comment by nicolas-raoul** [comment]
@niedzielski do you think you might have some power to get that done? :-)

**Comment by niedzielski** [comment]
https://gerrit.wikimedia.org/r/#/c/272212/
https://phabricator.wikimedia.org/T127623

**Comment by FlorianSW** [comment]
I think the better (any probably best) solution would be to fix https://phabricator.wikimedia.org/T127678 :)

**Comment by nicolas-raoul** [comment]
Fixed, thanks all :-)
