### ISSUE TITLE
Obtain WMF permission to use Wikimedia Commons logo

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#68]
It would make the app more recognizable to Commons users.
Also, the current logo that I quickly designed is quite ugly.

_A few years ago I used the Wikivoyage logo for [the non-official Wikivoyage app](https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikivoyage&hl=en) and after a few months a WMF lawyer got Google to take down the app. Conclusion: Before using the official logo, better make sure all layers have got the memo._

**Comment by slaporte** [comment]
Nice app! You can request a trademark license via the online form here: https://meta.wikimedia.org/wiki/Special:Contact/requestlicense

The Wikimedia trademarks team is usually pretty quick to respond, but feel free to ping me if you don't hear back.

**Comment by nicolas-raoul** [comment]
Sent thanks :-)

**Comment by nicolas-raoul** [comment]
Fixed :-)
