### ISSUE TITLE
User agent

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#80]
We must say who we are when making a request (in particular uploads I guess)

https://meta.wikimedia.org/wiki/Wikimedia_Apps/Developing_an_official_app

**Comment by misaochan** [comment]
Sorry, I'm probably just confused, but don't we already state who we are in the template each time an image is uploaded? All the images uploaded by our app are tagged with 'Uploaded by Android mobile app', right?

**Comment by nicolas-raoul** [comment]
I guess they also want httpd stats.
I'll try to do it this week!

**Comment by nicolas-raoul** [comment]
Already implemented it seems:
https://github.com/nicolas-raoul/apps-android-commons/blob/master/commons/src/main/java/fr/free/nrw/commons/CommonsApplication.java#L81
