### ISSUE TITLE
Build error: package com.github.varunpant.quadtree does not exist

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#81]
Am I mistaken, or Quadtree is not in the GitHub source code and thus a clean clone can't be built?

**Comment by misaochan** [comment]
Odd,  I could've sworn I added the jar when I was working on it. But I used the search function now and indeed there doesn't appear to be a quadtree jar anywhere. 

Not at the computer now but I'll try and see if I can add it tomorrow.

**Comment by misaochan** [comment]
Added the JAR that you sent me previously

**Comment by nicolas-raoul** [comment]
Thanks＾＾
