### ISSUE TITLE
Suggest uploading picture to Commons in notification bar

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#84]
When a user takes a picture with geotagging on and we can find a nearby category for it, we could show a notification suggesting that they upload it to Commons? Clicking the notification could take them directly to the title/desc screen. Of course, this function should be optional and can be disabled if the user doesn't want it.

Pros:
- Easier use: Instead of having to go to the app, go to gallery, select picture.... they just have to make one tap. 
- Reminds them that they can upload the pic to Commons

Cons:
- Would probably need more permissions than we currently have
- Not sure how to implement, would need to overhaul how and when categories are found, would also need to listen constantly, might drain battery?

Just a thought. :)

**Comment by nicolas-raoul** [comment]
All camera apps have a "Share" button that allows to send to our app, isn't
it enough?

**Comment by misaochan** [comment]
Hm, I can't seem to find that option in my camera - does it work for stock apps like Samsung's inbuilt one as well?

**Comment by nicolas-raoul** [comment]
It is probably in the viewing part. Do you have an easy way to see the
picture that you just took? Usually a small thumbnail of the last picture.

**Comment by misaochan** [comment]
Oh, that! It's pretty far down the 'Share' list, hahah. But yes it's there. :) Maybe we don't need this then.

**Comment by nicolas-raoul** [comment]
The apps you often share to come to the top.
UploadToCommons is currently at the top for me :-) followed by Gmail and a
few social network apps

**Comment by misaochan** [comment]
Gotcha, thanks! Easier to use that. :)
