### ISSUE TITLE
Migrate to Gradle

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#88]
That would make the project soooo much easier to build.
It is an important thing in order to get new volunteers.

**Comment by misaochan** [comment]
I agree 101%.

How would we manage the dependencies though? Many of the old ones are only hosted on a Maven repo right?

**Comment by nicolas-raoul** [comment]
I am sure many other Sherlock-using projects have moved to Gradle, we could spy and steal from them.

**Comment by nicolas-raoul** [comment]
http://actionbarsherlock.com/usage.html has a paragraph about Gradle, I tried yesterday but got errors like `Error:(90) Attribute "titleTextStyle" has already been defined`.

**Comment by misaochan** [comment]
I've always wondered about this - is continuing to use the Sherlock action bar really necessary in this Android version, compared to just using the stock Android action bar? It would take work to overhaul the code, but might it be better to remove this dependency in the long run?

**Comment by nicolas-raoul** [comment]
Indeed, in the long run it would be better.

I don't think it is a big priority though... in open source that's the kind
of things that often gets fixed within a year or two by a passing-by Good
Samaritan who happens to have done the exact same thing for other apps :-)

**Comment by domdomegg** [comment]
Got the project running gradle, but uses a load of old versions of dependencies. Check it out here (currently on master branch not gradle-support cause I screwed up git):
https://github.com/domdomegg/apps-android-commons

It would be good to get rid of many of the dependencies, definitely ABS should go and I don't think it can be too hard.

**Comment by nicolas-raoul** [comment]
Great!
Can you send a pull request if it works normally?
The dependencies can be removed afterwards I guess :-)

**Comment by domdomegg** [comment]
I'll just update the README, and I'll then start a pull request

**Comment by domdomegg** [comment]
Pull request #112 started

**Comment by misaochan** [comment]
Fixed by domdomegg.

**Comment by misaochan** [comment]
Hi @domdomegg ,

I'm getting a compiler warning when I view the source files, stating that package name doesn't correspond to file path. There appears to be an additional 'main/java' after the first 'main/java' - I don't recall this being the case in the Maven build. I've attached a screenshot:

![filepath](https://cloud.githubusercontent.com/assets/3611199/15883562/483f3bbc-2d9d-11e6-8e7d-5b837ad95925.jpg)

**Comment by domdomegg** [comment]
Very strange... Is that on master of nicolas-raoul? (Mine is broken atm, will fix soon)

**Comment by domdomegg** [comment]
Can now get that error, found a fix will push in a minute

**Comment by domdomegg** [comment]
See PR #120

**Comment by misaochan** [comment]
Nice, thanks @domdomegg
