### ISSUE TITLE
Make app available through F-Droid

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#93]
As suggested by a user on https://commons.wikimedia.org/wiki/Commons_talk:Mobile_app :

> It would be nice to have this app also available through F-Droid. Here's how to do it. ~★ pikolas [[mia diskuto]] 20:38, 25 March 2016 (UTC)

**Comment by nicolas-raoul** [comment]
Request created: https://f-droid.org/forums/topic/upload-to-commons-wikimedia-commons-app/
If someone could write a recipe it would be shipped faster though. I tip about that on the talk page :-)

**Comment by domdomegg** [comment]
#82

**Comment by nicolas-raoul** [comment]
@domdomegg Thanks for noticing this issue duplication! Let's move the discussion to the first one.
