### ISSUE TITLE
Android Studio 2.0+ issues with Maven imports

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#99]
Android Studio 2.0 and above does not appear to handle Maven integration, several Maven libraries/modules (ActionBarSherlock, etc) are not imported even when using the same import settings as previous successful imports. 

Using Android Studio 1.5 appears to solve the problem for now. Not sure if the issue is with Android Studio itself or just with the project's incompatibility with the new version? Or if I'm doing something wrong...

**Comment by misaochan** [comment]
I've edited the README accordingly.

**Comment by domdomegg** [comment]
Android Studio 2.0+ no longer supports maven, migration to gradle (#112) is a solution.

**Comment by misaochan** [comment]
Migrated to Gradle, this should not be an issue anymore.
